version: '3.1'

services:
  db:
    image: postgres:11.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=civ
    ports:
      - 5432:5432
    networks:
      - default

networks:
  default:
    ipam:
      config:
        - subnet: 172.16.250.0/24
