name: Build and deploy back
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Test and Build
        working-directory: backend
        run: |
          ./mvnw test
          ./mvnw clean install

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: civ-backend
          environment_name: CivBackend-env-1
          region: eu-west-3
          version_label: 1
          deployment_package: backend/target/civ-0.0.1-SNAPSHOT.jar