name: Build and deploy front
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test and Build
        working-directory: frontend
        run: |
          npm ci
          npm run build:ci
      
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            SOURCE: "frontend/dist/frontend/"
            REMOTE_HOST: "guilloy.fr"
            REMOTE_USER: "github"
            TARGET: "/var/www/htdocs/civ-static"

